#install.packages("KoNLP")
#install.packages("wordcloud")
#install.packages("stringr")
library(KoNLP)
library(wordcloud)
library(stringr)
useSejongDic()
buildDictionary(data.frame("따릉이", "ncn"))
raw <- readLines("dddddd.txt")
data1 <- sapply(raw, extractNoun, USE.NAMES = F)

head(data1)
cdata<-unlist(data1)
head(cdata,30)
data2<-gsub("\\d+", "", cdata)
data2<-gsub("따릉이","", data2)
data2<-gsub("자전거","", data2)
data2<-gsub("대여","", data2)
data2<-gsub("설치","", data2)
data2<-gsub("이용","", data2)
data2<-gsub("반납","", data2)
data2<-gsub("시간","", data2)
data2<-gsub("완료","", data2)
data2<-gsub("전화","", data2)
data2<-gsub("안녕","", data2)
data2<-gsub("처리","", data2)
data2<-gsub("시민","", data2)
data2<-gsub("사거리","", data2)
data2<-gsub("버스","", data2)
data2<-gsub("해서","", data2)
data2<-gsub("거치대","", data2)
data2<-gsub("아파트","", data2)
data2<-gsub("감사","", data2)
data2<-gsub("하게","", data2)
data2<-gsub("주민","", data2)

data2<-gsub("근처","", data2)
data2<-gsub("확인","", data2)
data2<-gsub("정기","", data2)
data2<-gsub("주변","", data2)
data2<-gsub("오늘","", data2)
data2<-gsub("연결","", data2)
data2<-gsub("생각","", data2)
data2<-gsub("문제","", data2)
data2<-gsub("장애","", data2)
data2<-gsub("사람","", data2)
data2<-gsub("언제","", data2)
data2<-gsub("답변","", data2)
data2<-gsub("들이","", data2)
data2<-gsub("번출구","", data2)
data2<-gsub("출구","", data2)
data2<-gsub("경우","", data2)
data2<-gsub("확인","", data2)
data2<-gsub("","", data2)

data2<-str_replace_all("[^[:alpha:]]","",data2)
data2<-Filter(function(x){nchar(x)>=2}, data2)
data2<-Filter(function(x){nchar(x)<=3}, data2)
head(unlist(data2), 30)
write(unlist(data2),"dd.txt")
data3<-read.table("dd.txt")
nrow(data3)
wordcount<-table(data3)
head(sort(wordcount, decreasing = T),50)

#wordCloud 만들기
#install.packages("RColorBrewer")
library(RColorBrewer)
palete <- brewer.pal(4, "Set1")
wordcloud(names(wordcount), freq = wordcount, scale = c(6,1), rot.per = 0.25, min.freq = 25, random.order = F, random.color = T, colors = palete)
legend(0.3, 1, "따릉이 시민의견수렴 게시글", cex = 1, fill = NA, border = NA, bg = "white", text.col = "red", text.font = 4, box.col = "red")
savePlot("2018년 따릉이 시민의견수렴 게시글.png", type = "png")
